// Source: public WordPress feed of notebookfromthevalley.com, retrieved October 8, 2026.
// Titles, dates and opening lines are quoted verbatim. One post containing placeholder text is excluded.
export const notebookUrl = 'https://notebookfromthevalley.com';
export type Article = { title: string; date: string; topic: string; lede: string; slug: string };
export const articles: Article[] = [
  { date: '2026-06-05', topic: 'Founding note', slug: 'these-are-my-notes-from-the-valley', title: 'These are my notes from the Valley.', lede: 'Notebook from the Valley was born from a simple observation.' },
  { date: '2026-06-01', topic: 'Policy', slug: 'inside-garrys-list-discussing-californias-future-with-governor-newsom', title: 'Inside Garry’s List: Discussing California’s Future with Governor Newsom', lede: 'One of the most interesting aspects of living in Silicon Valley is realizing that innovation is not only built inside startups, research labs, or venture capital firms. It is also shaped by public policy, local communities, and civic engagement.' },
  { date: '2026-05-30', topic: 'Companies', slug: 'nvidia-the-company-powering-the-ai-revolution', title: 'NVIDIA: The Company Powering the AI Revolution', lede: 'A few years ago, most people knew NVIDIA for one thing: graphics cards.' },
  { date: '2026-05-25', topic: 'Perspective', slug: 'america-at-250-reflecting-on-independence-innovation-and-the-future', title: 'America at 250: Reflecting on Independence, Innovation, and the Future', lede: 'In 2026, the United States will celebrate its 250th anniversary.' },
  { date: '2026-05-24', topic: 'Capital', slug: 'andreessen-horowitz-the-name-you-hear-everywhere-in-silicon-valley', title: 'Andreessen Horowitz: The Name You Hear Everywhere in Silicon Valley', lede: 'Before moving to Silicon Valley, I knew Andreessen Horowitz—better known as a16z—the same way many people outside the Valley do. I knew the name.' },
  { date: '2026-05-14', topic: 'People', slug: 'fei-fei-li-the-godmother-of-ai', title: 'Fei-Fei Li: The Godmother of AI', lede: 'Yet many of these advances rest on foundations built years earlier by researchers whose names are less familiar to the general public.' },
  { date: '2026-05-07', topic: 'Essay', slug: 'the-people-who-build-civilization-rarely-become-famous', title: 'The people who build civilization rarely become famous', lede: 'When people think about progress, they usually think about famous names.' },
  { date: '2026-04-20', topic: 'Infrastructure', slug: 'why-infrastructure-is-becoming-the-most-important-technology-sector-of-the-ai-era', title: 'Why infrastructure is becoming the most important technology sector of the AI era', lede: 'For most of the last twenty years, software dominated the technology industry.' },
  { date: '2026-04-16', topic: 'Essay', slug: 'we-are-living-through-the-second-age-of-engineering', title: 'We are living through the second age of engineering', lede: 'For much of the twentieth century, engineers were the heroes of progress.' },
  { date: '2026-04-15', topic: 'Field visit', slug: 'visiting-apple-park-where-vision-becomes-reality', title: 'Visiting Apple Park: Where Vision Becomes Reality', lede: 'Few companies have shaped the modern world as profoundly as Apple.' },
  { date: '2026-04-07', topic: 'Firsthand', slug: 'one-year-in-silicon-valley', title: 'One year in Silicon Valley', lede: 'When I moved from France to California in the summer of 2025, I expected to find the epicenter of artificial intelligence.' },
  { date: '2026-04-06', topic: 'People', slug: 'sam-altman-the-face-of-the-ai-era', title: 'Sam Altman: The Face of the AI Era', lede: 'A few years ago, most people had never heard of Sam Altman. Today, that is no longer the case.' },
  { date: '2026-04-03', topic: 'Conferences', slug: 'what-nvidia-gtc-ces-google-i-o-and-dell-technologies-world-reveal-about-the-next-decade-of-computing', title: 'What Nvidia GTC, CES, Google I/O and Dell Technologies World reveal about the next decade of computing', lede: 'One of the advantages of spending time in Silicon Valley is being able to watch technology evolve before it becomes ordinary.' },
  { date: '2026-03-18', topic: 'Ecosystem', slug: 'the-invisible-university-of-silicon-valley', title: 'The invisible university of Silicon Valley', lede: 'What I did not expect before moving here was the sheer density of learning taking place every single day outside traditional institutions.' },
  { date: '2026-03-10', topic: 'Startups', slug: 'y-combinator-silicon-valleys-ultimate-startup-stamp-of-approval', title: 'Y Combinator: Silicon Valley’s Ultimate Startup Stamp of Approval', lede: 'It is part accelerator. Part institution. Part legend.' },
  { date: '2026-03-02', topic: 'Ecosystem', slug: 'luma-the-app-that-taught-me-how-silicon-valley-really-works', title: 'Luma: The App That Taught Me How Silicon Valley Really Works', lede: 'One of the first things I learned is that much of Silicon Valley actually happens through events.' },
  { date: '2026-02-22', topic: 'Firsthand', slug: 'what-silicon-valley-taught-me-about-ambition', title: 'What Silicon Valley taught me about ambition', lede: 'When I left France for California in the summer of 2025, I was not only moving to another country. I was moving toward an idea.' },
  { date: '2026-02-19', topic: 'Careers', slug: 'why-the-most-valuable-people-in-silicon-valley-are-not-specialists', title: 'Why the most valuable people in Silicon Valley are not specialists', lede: 'Before moving to Silicon Valley, I assumed expertise was the ultimate competitive advantage.' },
  { date: '2026-02-13', topic: 'Infrastructure', slug: 'building-ai-infrastructure-between-europe-and-silicon-valley', title: 'Building AI infrastructure between Europe and Silicon Valley', lede: 'Moving from France to Silicon Valley changed the way I think about technology.' },
  { date: '2026-02-02', topic: 'Trends', slug: 'longevity-and-the-rise-of-the-human-operating-system', title: 'Longevity and the rise of the human operating system', lede: 'One of the most surprising trends I have observed during my first year in Silicon Valley has little to do with artificial intelligence.' },
  { date: '2026-01-27', topic: 'AI', slug: 'the-rise-of-physical-ai', title: 'The rise of physical AI', lede: 'For much of the last decade, artificial intelligence lived on screens.' },
  { date: '2026-01-15', topic: 'Ecosystem', slug: 'in-silicon-valley-networking-is-the-new-nightlife', title: 'In Silicon Valley, Networking Is the New Nightlife', lede: 'The social life here is fundamentally different from what I experienced in France.' },
  { date: '2026-01-14', topic: 'Infrastructure', slug: 'ai-energy-and-water-the-sustainability-challenge-nobody-talks-about', title: 'AI, energy and water: the sustainability challenge nobody talks about', lede: 'Artificial intelligence is often presented as an immaterial technology.' },
  { date: '2026-01-08', topic: 'Firsthand', slug: 'waymo-the-first-time-i-felt-like-i-was-living-in-the-future', title: 'Waymo: The First Time I Felt Like I Was Living in the Future', lede: 'Before moving to Silicon Valley, Waymo felt almost like a myth.' },
  { date: '2026-01-03', topic: 'Infrastructure', slug: 'the-future-will-not-run-entirely-in-the-cloud', title: 'The future will not run entirely in the cloud', lede: 'For more than a decade, the cloud has been one of the dominant narratives in technology.' }
];
export const articleHref = (a: Article) => `${notebookUrl}/${a.slug}/`;
export const formatDate = (iso: string) => new Date(`${iso}T12:00:00Z`).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric', timeZone: 'UTC' }).toUpperCase();
// Curated for the homepage: the founding note plus a cross-section of infrastructure, firsthand reporting and companies.
export const featuredSlugs = ['these-are-my-notes-from-the-valley', 'why-infrastructure-is-becoming-the-most-important-technology-sector-of-the-ai-era', 'one-year-in-silicon-valley', 'nvidia-the-company-powering-the-ai-revolution', 'the-invisible-university-of-silicon-valley', 'waymo-the-first-time-i-felt-like-i-was-living-in-the-future'];
export const featured = featuredSlugs.map(s => articles.find(a => a.slug === s)!);
