import type { Metadata } from 'next';
import Link from 'next/link';
import { projects } from '@/lib/projects';
import { ProjectMedia } from '@/components/media';
import { Signature } from '@/components/signature';
export const metadata: Metadata = { title: 'Selected work', description: 'Four builds in accountable autonomy — ORQO, Intent Firewall, Handshake and Steward — and Notebook from the Valley, an independent technology publication.' };
export default function Work() {
  return <div className="work-page section-pad"><div className="page-intro"><p className="eyebrow">THE BUILDER’S UNIVERSE / WORK INDEX</p><h1>Ideas become<br/><em>things you can use.</em></h1><p>Four builds share an interest in agents that act with context, respect constraints, and leave evidence behind. A fifth project, an independent publication, documents the ecosystem they come from.</p></div><div className="work-index-meta"><span>SELECTED WORK / 01—05</span><span>2026</span></div>{projects.map(p => <article className={`work-entry work-${p.kind ?? 'build'}`} key={p.slug} style={{'--project-accent':p.accent} as React.CSSProperties}><div className="work-entry-header"><span className="eyebrow">{p.number} / {p.category}</span><span className="project-status">{p.status}</span></div><div className="work-entry-body"><div className="work-entry-copy"><span className="work-entry-number" aria-hidden="true">{p.number}</span><Link href={`/work/${p.slug}`} className="work-entry-title"><h2>{p.name}</h2><span aria-hidden="true">↗</span></Link><p className="work-entry-hook">{p.hook}</p><div className="work-entry-summary"><p>{p.summary}</p><Link className="text-link" href={`/work/${p.slug}`}>Explore case study <span>↗</span></Link></div><Signature slug={p.slug} caption={false} className="work-sig"/></div><div className="work-entry-shot" data-tilt><ProjectMedia src={p.image} alt={p.imageAlt} caption={p.caption} label={p.kind === 'media' ? 'PUBLICATION CAPTURE / 2026' : undefined}/></div></div></article>)}</div>;
}
