import Link from 'next/link';
import { Hero } from '@/components/hero';
import { ProjectMedia } from '@/components/media';
import { Constellation } from '@/components/constellation';
import { Infrastructure } from '@/components/infrastructure';
import { NotebookSection } from '@/components/notebook';
import { builds, projects, siteOrigin } from '@/lib/projects';
export default function Home() {
  const orqo = projects[0];
  return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html: JSON.stringify({'@context':'https://schema.org','@type':'Person',name:'Vincent Leguide',url:siteOrigin,sameAs:['https://github.com/vincentleg'],jobTitle:'Builder, business developer and writer',nationality:'French',homeLocation:'San Francisco Bay Area',worksFor:{'@type':'Organization',name:'INFODIP'}})}}/><Hero/><section id="orqo" className="flagship section-pad" aria-labelledby="orqo-title"><div className="section-kicker"><span>02 / CURRENTLY BUILDING</span><span className="status"><i/> IN DEVELOPMENT</span></div><div className="flagship-intro" data-reveal><div><p className="eyebrow">THE FLAGSHIP PROJECT</p><h2 id="orqo-title">Relationships.<br/>Meet <em>possibility.</em></h2></div><div className="flagship-description"><div className="orqo-wordmark"><span aria-hidden="true">◎</span> ORQO</div><p>{orqo.summary}</p><Link className="text-link" href="/work/orqo">Enter the case study <span>↗</span></Link></div></div><div className="flagship-watermark" aria-hidden="true">ORQO</div><div className="flagship-stage"><ProjectMedia src={orqo.image} alt={orqo.imageAlt} caption={orqo.caption}/></div><div className="flagship-bottom"><span>RESEARCH → REASON → CHALLENGE → CONNECT</span><span>EVIDENCE BEFORE OPPORTUNITY.</span></div></section><section className="selected section-pad" aria-labelledby="selected-title"><div className="section-kicker"><span>03 / SELECTED BUILDS</span><span>EXPERIMENTS IN ACCOUNTABLE AUTONOMY</span></div><div className="section-heading" data-reveal><h2 id="selected-title">Different problems.<br/><em>A common instinct.</em></h2><Link href="/work" className="text-link">All projects <span>↗</span></Link></div><div className="builds">{builds.slice(1).map(p => <article className={`build build-${p.slug}`} key={p.slug} style={{'--project-accent':p.accent} as React.CSSProperties} data-reveal><div className="build-info"><span className="eyebrow">{p.number} / {p.category}</span><Link className="build-title" href={`/work/${p.slug}`}><h3>{p.name}</h3><span aria-hidden="true">↗</span></Link><p className="build-hook">{p.hook}</p><p>{p.summary}</p><span className="project-status">{p.status}</span><Link className="text-link" href={`/work/${p.slug}`}>Read the case study <span>↗</span></Link></div><div className="build-visual"><div className="build-symbol" aria-hidden="true">{p.slug === 'intent-firewall' ? '⌘' : p.slug === 'handshake' ? '◎' : '◌'}</div><ProjectMedia src={p.image} alt={p.imageAlt}/><span className="build-visual-caption">AUTHENTIC PRODUCT CAPTURE / {p.number}</span></div></article>)}</div></section><Constellation/><NotebookSection/><Infrastructure/></>;
}
