'use client';
import Link from 'next/link';
import { useState } from 'react';
import { projects } from '@/lib/projects';
export function Constellation() {
  const [active, setActive] = useState(0);
  const positions = projects.map((_, index) => { const angle = -Math.PI / 2 + index * Math.PI * 2 / projects.length; return { x: 50 + Math.cos(angle) * 35, y: 50 + Math.sin(angle) * 35 }; });
  return <section className="constellation section-pad" aria-labelledby="constellation-title"><div className="section-kicker"><span>04 / THE CONNECTIONS</span><span>FOUR BUILDS. ONE NOTEBOOK.</span></div><div className="constellation-layout"><div className="constellation-copy"><p className="eyebrow">NOT ISOLATED IDEAS.</p><h2 id="constellation-title">A connected<br/><em>way of thinking.</em></h2><p>How do we give agents the freedom to act, and the judgment to know when to ask? Four builds explore the question. One notebook watches the ecosystem it comes from.</p><div className="constellation-detail" aria-live="polite"><span className="eyebrow" style={{color:projects[active].accent}}>{projects[active].number} / {projects[active].category}</span><h3>{projects[active].name}</h3><p>{projects[active].summary}</p><Link className="text-link" href={`/work/${projects[active].slug}`}>Explore this project <span>↗</span></Link></div></div><div className="star-map"><svg viewBox="0 0 100 100" aria-hidden="true"><circle cx="50" cy="50" r="35"/><circle cx="50" cy="50" r="21"/><circle cx="50" cy="50" r="46"/>{positions.map((p,i) => <g key={i}><line className={active === i ? 'active-line' : ''} x1="50" y1="50" x2={p.x} y2={p.y}/><line x1={p.x} y1={p.y} x2={positions[(i + 1) % positions.length].x} y2={positions[(i + 1) % positions.length].y}/></g>)}{projects.map((p,i) => p.kind === 'media' && positions.map((q,j) => j !== i && Math.abs(j - i) !== 1 && Math.abs(j - i) !== projects.length - 1 && <line key={`${i}-${j}`} className="media-line" x1={positions[i].x} y1={positions[i].y} x2={q.x} y2={q.y}/>))}</svg><div className="map-core" aria-hidden="true">VL<span>SHARED INTENT</span></div>{projects.map((p,i) => <Link href={`/work/${p.slug}`} key={p.slug} className={`star-node ${p.kind === 'media' ? 'star-media' : ''} ${active === i ? 'active' : ''}`} style={{ left: `${positions[i].x}%`, top: `${positions[i].y}%`, '--node-accent': p.accent } as React.CSSProperties} onMouseEnter={() => setActive(i)} onFocus={() => setActive(i)}><span className="star-dot"/><span className="node-name">{p.name}<small>{p.number} / VIEW PROJECT ↗</small></span></Link>)}</div></div></section>;
}
