import { projects } from '@/lib/projects';
import { ProjectVisual } from './project-visual';
import { ProjectMedia } from './media';

export function ProjectChapters() {
  return <div className="project-chapters section-pad">{projects.map(p => <article id={`project-${p.slug}`} key={p.slug} className="project-chapter work-tile" style={{ '--project-accent': p.accent } as React.CSSProperties}>
    <div className="chapter-heading"><span className="chapter-number">{p.number}</span><p className="eyebrow">{p.category}</p><span className="project-status">{p.status}</span></div>
    <div className="chapter-layout" data-reveal><div className="chapter-copy"><h2>{p.name}</h2><p className="chapter-hook">{p.hook}</p><p>{p.summary}</p><div className="chapter-links">{p.links.map(link => <a className="text-link" key={link.href} href={link.href} target="_blank" rel="noopener noreferrer">{link.label}<span aria-hidden="true">↗</span></a>)}</div><ul className="chapter-stack" aria-label="Technologies and approach">{p.stack.map(s => <li key={s}>{s}</li>)}</ul></div>
      <div><a className="work-tile-visual" href={p.image || `#details-${p.slug}`} target={p.image ? '_blank' : undefined} rel={p.image ? 'noopener noreferrer' : undefined} aria-label={`View ${p.name} ${p.image ? 'full-size screenshot' : 'details'}`}><ProjectVisual project={p}/></a><p className="chapter-caption">{p.caption || 'Project concept and workflow'}</p></div></div>
    <details id={`details-${p.slug}`} className="chapter-details"><summary>Inside the project <span>Approach, screenshots & honest status <i aria-hidden="true">+</i></span></summary><div className="chapter-expanded"><div className="chapter-story"><div><h3>{p.kind === 'media' ? 'Why I write' : 'The problem'}</h3><p>{p.problem}</p></div><div><h3>The approach</h3><p>{p.approach}</p></div><div><h3>What comes next</h3><p>{p.next}</p></div></div><h3>What’s real, and what’s still in progress</h3><ul className="chapter-ledger">{p.ledger.map(l => <li key={l.capability}><h4>{l.capability}</h4><span>{l.status}</span><p>{l.evidence}</p>{l.href && <a href={l.href} target="_blank" rel="noopener noreferrer">View source ↗</a>}</li>)}</ul>{p.gallery.map(g => <ProjectMedia key={g.src} {...g}/>)}</div></details>
  </article>)}</div>;
}
export function Journey() {
  return <section id="journey" className="journey section-pad" aria-labelledby="journey-title"><div className="journey-intro" data-reveal><p className="eyebrow">MY JOURNEY · FRANCE → CALIFORNIA</p><h2 id="journey-title">Different horizons.<br/>The same <em>curiosity.</em></h2><p>I’ve always been drawn to technology, entrepreneurship, and the people imagining the future. Silicon Valley is where those interests meet — and where I’m turning curiosity into things I can build and share.</p></div><ol className="journey-track"><li data-reveal><span className="journey-date">01 / THE FOUNDATION</span><h3>Making AI more sustainable.</h3><p>Before California, I spent roughly five years working around sustainable AI infrastructure in France: immersion cooling, heat recovery, and energy-efficient computing. It taught me to think about what technology needs in the real world.</p></li><li data-reveal><span className="journey-date">02 / AUGUST 2025</span><h3>A one-way move. A wider world.</h3><p>I moved to the San Francisco Bay Area to get closer to the founders, builders, and ideas shaping what comes next. Today I represent INFODIP in the US and develop technology partnerships across the ecosystem.</p></li><li data-reveal><span className="journey-date">03 / THE CHAPTER I’M WRITING</span><h3>Build. Meet people. Take notes.</h3><p>I’m building my own AI products and learning through experiments. I also founded Notebook from the Valley to document the people, companies, ideas, and technologies I encounter along the way.</p></li></ol></section>;
}
