import { chromium } from '@playwright/test';
const origin = process.env.REVIEW_URL || 'http://127.0.0.1:3100';
const browser = await chromium.launch({args:['--enable-unsafe-swiftshader']});
const page = await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});
page.on('console', m => { if(m.type() === 'error') console.error(m.text()); });
await page.goto(origin);
await page.locator('.hero canvas').waitFor();
await page.waitForTimeout(1000);
await page.screenshot({path:'/tmp/vincent-desktop.png'});
await page.locator('#project-orqo').scrollIntoViewIfNeeded(); await page.waitForTimeout(1200);
await page.screenshot({path:'/tmp/vincent-orqo.png'});
await page.emulateMedia({reducedMotion:'reduce'}); await page.goto(origin);
for (const img of await page.locator('main img:visible').all()) await img.scrollIntoViewIfNeeded();
await page.screenshot({path:'/tmp/vincent-full.png',fullPage:true});
await page.setViewportSize({width:390,height:844}); await page.emulateMedia({reducedMotion:'no-preference'}); await page.goto(origin);
await page.waitForTimeout(1200); await page.screenshot({path:'/tmp/vincent-mobile-hero.png'});
await page.emulateMedia({reducedMotion:'reduce'}); await page.reload();
for (const img of await page.locator('main img:visible').all()) await img.scrollIntoViewIfNeeded();
await page.screenshot({path:'/tmp/vincent-mobile.png',fullPage:true});
await page.goto(`${origin}/work/intent-firewall`); await page.screenshot({path:'/tmp/vincent-case-mobile.png',fullPage:true});
await browser.close();
